"""init_system_tables

Revision ID: 5eeca545b614
Revises: 
Create Date: 2026-02-11 09:33:16.190669

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5eeca545b614'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('system_dept',
    sa.Column('name', sa.String(length=30), nullable=False, comment='部门名称'),
    sa.Column('parent_id', sa.BigInteger(), nullable=False, comment='父部门id'),
    sa.Column('sort', sa.Integer(), nullable=False, comment='显示顺序'),
    sa.Column('leader_user_id', sa.BigInteger(), nullable=True, comment='负责人'),
    sa.Column('phone', sa.String(length=11), nullable=True, comment='联系电话'),
    sa.Column('email', sa.String(length=50), nullable=True, comment='邮箱'),
    sa.Column('status', sa.SmallInteger(), nullable=False, comment='部门状态'),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False, comment='主键'),
    sa.Column('creator', sa.String(length=64), nullable=True, comment='创建者'),
    sa.Column('create_time', sa.DateTime(), nullable=False, comment='创建时间'),
    sa.Column('updater', sa.String(length=64), nullable=True, comment='更新者'),
    sa.Column('update_time', sa.DateTime(), nullable=False, comment='更新时间'),
    sa.Column('deleted', sa.SmallInteger(), nullable=False, comment='是否删除'),
    sa.Column('tenant_id', sa.BigInteger(), nullable=False, comment='租户编号'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('system_dict_data',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False, comment='字典编码'),
    sa.Column('sort', sa.Integer(), nullable=False, comment='字典排序'),
    sa.Column('label', sa.String(length=100), nullable=False, comment='字典标签'),
    sa.Column('value', sa.String(length=100), nullable=False, comment='字典键值'),
    sa.Column('dict_type', sa.String(length=100), nullable=False, comment='字典类型'),
    sa.Column('status', sa.SmallInteger(), nullable=False, comment='状态（0正常 1停用）'),
    sa.Column('color_type', sa.String(length=100), nullable=True, comment='颜色类型'),
    sa.Column('css_class', sa.String(length=100), nullable=True, comment='css 样式'),
    sa.Column('remark', sa.String(length=500), nullable=True, comment='备注'),
    sa.Column('creator', sa.String(length=64), nullable=True, comment='创建者'),
    sa.Column('create_time', sa.DateTime(), nullable=False, comment='创建时间'),
    sa.Column('updater', sa.String(length=64), nullable=True, comment='更新者'),
    sa.Column('update_time', sa.DateTime(), nullable=False, comment='更新时间'),
    sa.Column('deleted', sa.SmallInteger(), nullable=False, comment='是否删除'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('system_dict_type',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False, comment='字典主键'),
    sa.Column('name', sa.String(length=100), nullable=False, comment='字典名称'),
    sa.Column('type', sa.String(length=100), nullable=False, comment='字典类型'),
    sa.Column('status', sa.SmallInteger(), nullable=False, comment='状态（0正常 1停用）'),
    sa.Column('remark', sa.String(length=500), nullable=True, comment='备注'),
    sa.Column('creator', sa.String(length=64), nullable=True, comment='创建者'),
    sa.Column('create_time', sa.DateTime(), nullable=False, comment='创建时间'),
    sa.Column('updater', sa.String(length=64), nullable=True, comment='更新者'),
    sa.Column('update_time', sa.DateTime(), nullable=False, comment='更新时间'),
    sa.Column('deleted', sa.SmallInteger(), nullable=False, comment='是否删除'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('system_login_log',
    sa.Column('log_type', sa.SmallInteger(), nullable=False, comment='日志类型'),
    sa.Column('username', sa.String(length=50), nullable=False, comment='用户账号'),
    sa.Column('user_ip', sa.String(length=50), nullable=True, comment='登录IP'),
    sa.Column('user_agent', sa.String(length=512), nullable=True, comment='浏览器UA'),
    sa.Column('result', sa.SmallInteger(), nullable=False, comment='登录结果'),
    sa.Column('user_id', sa.BigInteger(), nullable=True, comment='用户编号'),
    sa.Column('user_type', sa.SmallInteger(), nullable=False, comment='用户类型'),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False, comment='主键'),
    sa.Column('creator', sa.String(length=64), nullable=True, comment='创建者'),
    sa.Column('create_time', sa.DateTime(), nullable=False, comment='创建时间'),
    sa.Column('updater', sa.String(length=64), nullable=True, comment='更新者'),
    sa.Column('update_time', sa.DateTime(), nullable=False, comment='更新时间'),
    sa.Column('deleted', sa.SmallInteger(), nullable=False, comment='是否删除'),
    sa.Column('tenant_id', sa.BigInteger(), nullable=False, comment='租户编号'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('system_menu',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False, comment='菜单ID'),
    sa.Column('name', sa.String(length=50), nullable=False, comment='菜单名称'),
    sa.Column('permission', sa.String(length=100), nullable=False, comment='权限标识'),
    sa.Column('type', sa.SmallInteger(), nullable=False, comment='菜单类型'),
    sa.Column('sort', sa.Integer(), nullable=False, comment='显示顺序'),
    sa.Column('parent_id', sa.BigInteger(), nullable=False, comment='父菜单ID'),
    sa.Column('path', sa.String(length=200), nullable=True, comment='路由地址'),
    sa.Column('icon', sa.String(length=100), nullable=True, comment='菜单图标'),
    sa.Column('component', sa.String(length=255), nullable=True, comment='组件路径'),
    sa.Column('component_name', sa.String(length=255), nullable=True, comment='组件名'),
    sa.Column('status', sa.SmallInteger(), nullable=False, comment='菜单状态'),
    sa.Column('visible', sa.Boolean(), nullable=False, comment='是否可见'),
    sa.Column('keep_alive', sa.Boolean(), nullable=False, comment='是否缓存'),
    sa.Column('always_show', sa.Boolean(), nullable=False, comment='是否总是显示'),
    sa.Column('creator', sa.String(length=64), nullable=True, comment='创建者'),
    sa.Column('create_time', sa.DateTime(), nullable=False, comment='创建时间'),
    sa.Column('updater', sa.String(length=64), nullable=True, comment='更新者'),
    sa.Column('update_time', sa.DateTime(), nullable=False, comment='更新时间'),
    sa.Column('deleted', sa.SmallInteger(), nullable=False, comment='是否删除'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('system_notice',
    sa.Column('title', sa.String(length=50), nullable=False, comment='公告标题'),
    sa.Column('type', sa.SmallInteger(), nullable=False, comment='公告类型（1通知 2公告）'),
    sa.Column('content', sa.Text(), nullable=False, comment='公告内容'),
    sa.Column('status', sa.SmallInteger(), nullable=False, comment='公告状态（0正常 1关闭）'),
    sa.Column('remark', sa.String(length=255), nullable=True, comment='备注'),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False, comment='主键'),
    sa.Column('creator', sa.String(length=64), nullable=True, comment='创建者'),
    sa.Column('create_time', sa.DateTime(), nullable=False, comment='创建时间'),
    sa.Column('updater', sa.String(length=64), nullable=True, comment='更新者'),
    sa.Column('update_time', sa.DateTime(), nullable=False, comment='更新时间'),
    sa.Column('deleted', sa.SmallInteger(), nullable=False, comment='是否删除'),
    sa.Column('tenant_id', sa.BigInteger(), nullable=False, comment='租户编号'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('system_oauth2_access_token',
    sa.Column('user_id', sa.BigInteger(), nullable=False, comment='用户编号'),
    sa.Column('user_type', sa.SmallInteger(), nullable=False, comment='用户类型'),
    sa.Column('user_info', sa.String(length=512), nullable=False, comment='用户信息'),
    sa.Column('access_token', sa.String(length=255), nullable=False, comment='访问令牌'),
    sa.Column('refresh_token', sa.String(length=32), nullable=False, comment='刷新令牌'),
    sa.Column('client_id', sa.String(length=255), nullable=False, comment='客户端编号'),
    sa.Column('scopes', sa.String(length=255), nullable=True, comment='授权范围'),
    sa.Column('expires_time', sa.DateTime(), nullable=False, comment='过期时间'),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False, comment='主键'),
    sa.Column('creator', sa.String(length=64), nullable=True, comment='创建者'),
    sa.Column('create_time', sa.DateTime(), nullable=False, comment='创建时间'),
    sa.Column('updater', sa.String(length=64), nullable=True, comment='更新者'),
    sa.Column('update_time', sa.DateTime(), nullable=False, comment='更新时间'),
    sa.Column('deleted', sa.SmallInteger(), nullable=False, comment='是否删除'),
    sa.Column('tenant_id', sa.BigInteger(), nullable=False, comment='租户编号'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('system_oauth2_client',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False, comment='编号'),
    sa.Column('client_id', sa.String(length=255), nullable=False, comment='客户端编号'),
    sa.Column('secret', sa.String(length=255), nullable=False, comment='客户端密钥'),
    sa.Column('name', sa.String(length=255), nullable=False, comment='应用名'),
    sa.Column('logo', sa.String(length=255), nullable=False, comment='应用图标'),
    sa.Column('description', sa.String(length=255), nullable=True, comment='应用描述'),
    sa.Column('status', sa.SmallInteger(), nullable=False, comment='状态'),
    sa.Column('access_token_validity_seconds', sa.Integer(), nullable=False, comment='访问令牌的有效期'),
    sa.Column('refresh_token_validity_seconds', sa.Integer(), nullable=False, comment='刷新令牌的有效期'),
    sa.Column('redirect_uris', sa.String(length=255), nullable=False, comment='可重定向的 URI 地址'),
    sa.Column('authorized_grant_types', sa.String(length=255), nullable=False, comment='授权类型'),
    sa.Column('scopes', sa.String(length=255), nullable=True, comment='授权范围'),
    sa.Column('auto_approve_scopes', sa.String(length=255), nullable=True, comment='自动通过的授权范围'),
    sa.Column('authorities', sa.String(length=255), nullable=True, comment='权限'),
    sa.Column('resource_ids', sa.String(length=255), nullable=True, comment='资源'),
    sa.Column('additional_information', sa.String(length=4096), nullable=True, comment='附加信息'),
    sa.Column('creator', sa.String(length=64), nullable=True, comment='创建者'),
    sa.Column('create_time', sa.DateTime(), nullable=False, comment='创建时间'),
    sa.Column('updater', sa.String(length=64), nullable=True, comment='更新者'),
    sa.Column('update_time', sa.DateTime(), nullable=False, comment='更新时间'),
    sa.Column('deleted', sa.SmallInteger(), nullable=False, comment='是否删除'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('system_oauth2_refresh_token',
    sa.Column('user_id', sa.BigInteger(), nullable=False, comment='用户编号'),
    sa.Column('refresh_token', sa.String(length=32), nullable=False, comment='刷新令牌'),
    sa.Column('user_type', sa.SmallInteger(), nullable=False, comment='用户类型'),
    sa.Column('client_id', sa.String(length=255), nullable=False, comment='客户端编号'),
    sa.Column('scopes', sa.String(length=255), nullable=True, comment='授权范围'),
    sa.Column('expires_time', sa.DateTime(), nullable=False, comment='过期时间'),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False, comment='主键'),
    sa.Column('creator', sa.String(length=64), nullable=True, comment='创建者'),
    sa.Column('create_time', sa.DateTime(), nullable=False, comment='创建时间'),
    sa.Column('updater', sa.String(length=64), nullable=True, comment='更新者'),
    sa.Column('update_time', sa.DateTime(), nullable=False, comment='更新时间'),
    sa.Column('deleted', sa.SmallInteger(), nullable=False, comment='是否删除'),
    sa.Column('tenant_id', sa.BigInteger(), nullable=False, comment='租户编号'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('system_operate_log',
    sa.Column('trace_id', sa.String(length=64), nullable=False, comment='链路追踪编号'),
    sa.Column('user_id', sa.BigInteger(), nullable=False, comment='用户编号'),
    sa.Column('user_type', sa.SmallInteger(), nullable=False, comment='用户类型'),
    sa.Column('module', sa.String(length=50), nullable=False, comment='操作模块'),
    sa.Column('name', sa.String(length=50), nullable=False, comment='操作名'),
    sa.Column('type', sa.SmallInteger(), nullable=False, comment='操作分类'),
    sa.Column('content', sa.String(length=2000), nullable=False, comment='操作内容'),
    sa.Column('exts', sa.String(length=2000), nullable=False, comment='拓展字段'),
    sa.Column('request_method', sa.String(length=16), nullable=True, comment='请求方法名'),
    sa.Column('request_url', sa.String(length=255), nullable=True, comment='请求地址'),
    sa.Column('user_ip', sa.String(length=50), nullable=True, comment='用户 IP'),
    sa.Column('user_agent', sa.String(length=512), nullable=True, comment='浏览器 UA'),
    sa.Column('java_method', sa.String(length=512), nullable=False, comment='Java 方法名'),
    sa.Column('java_method_args', sa.Text(), nullable=True, comment='Java 方法参数'),
    sa.Column('result_code', sa.Integer(), nullable=False, comment='结果码'),
    sa.Column('result_msg', sa.String(length=512), nullable=True, comment='结果提示'),
    sa.Column('result_data', sa.Text(), nullable=True, comment='结果数据'),
    sa.Column('duration', sa.Integer(), nullable=False, comment='执行时长'),
    sa.Column('start_time', sa.DateTime(), nullable=False, comment='开始时间'),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False, comment='主键'),
    sa.Column('creator', sa.String(length=64), nullable=True, comment='创建者'),
    sa.Column('create_time', sa.DateTime(), nullable=False, comment='创建时间'),
    sa.Column('updater', sa.String(length=64), nullable=True, comment='更新者'),
    sa.Column('update_time', sa.DateTime(), nullable=False, comment='更新时间'),
    sa.Column('deleted', sa.SmallInteger(), nullable=False, comment='是否删除'),
    sa.Column('tenant_id', sa.BigInteger(), nullable=False, comment='租户编号'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('system_post',
    sa.Column('code', sa.String(length=64), nullable=False, comment='岗位编码'),
    sa.Column('name', sa.String(length=50), nullable=False, comment='岗位名称'),
    sa.Column('sort', sa.Integer(), nullable=False, comment='显示顺序'),
    sa.Column('status', sa.SmallInteger(), nullable=False, comment='状态（0正常 1停用）'),
    sa.Column('remark', sa.String(length=500), nullable=True, comment='备注'),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False, comment='主键'),
    sa.Column('creator', sa.String(length=64), nullable=True, comment='创建者'),
    sa.Column('create_time', sa.DateTime(), nullable=False, comment='创建时间'),
    sa.Column('updater', sa.String(length=64), nullable=True, comment='更新者'),
    sa.Column('update_time', sa.DateTime(), nullable=False, comment='更新时间'),
    sa.Column('deleted', sa.SmallInteger(), nullable=False, comment='是否删除'),
    sa.Column('tenant_id', sa.BigInteger(), nullable=False, comment='租户编号'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('system_role',
    sa.Column('name', sa.String(length=30), nullable=False, comment='角色名称'),
    sa.Column('code', sa.String(length=100), nullable=False, comment='角色权限字符串'),
    sa.Column('sort', sa.Integer(), nullable=False, comment='显示顺序'),
    sa.Column('data_scope', sa.SmallInteger(), nullable=False, comment='数据范围'),
    sa.Column('data_scope_dept_ids', sa.String(length=500), nullable=False, comment='数据范围(指定部门数组)'),
    sa.Column('status', sa.SmallInteger(), nullable=False, comment='角色状态'),
    sa.Column('type', sa.SmallInteger(), nullable=False, comment='角色类型'),
    sa.Column('remark', sa.String(length=500), nullable=True, comment='备注'),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False, comment='主键'),
    sa.Column('creator', sa.String(length=64), nullable=True, comment='创建者'),
    sa.Column('create_time', sa.DateTime(), nullable=False, comment='创建时间'),
    sa.Column('updater', sa.String(length=64), nullable=True, comment='更新者'),
    sa.Column('update_time', sa.DateTime(), nullable=False, comment='更新时间'),
    sa.Column('deleted', sa.SmallInteger(), nullable=False, comment='是否删除'),
    sa.Column('tenant_id', sa.BigInteger(), nullable=False, comment='租户编号'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('system_role_menu',
    sa.Column('role_id', sa.BigInteger(), nullable=False, comment='角色ID'),
    sa.Column('menu_id', sa.BigInteger(), nullable=False, comment='菜单ID'),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False, comment='主键'),
    sa.Column('creator', sa.String(length=64), nullable=True, comment='创建者'),
    sa.Column('create_time', sa.DateTime(), nullable=False, comment='创建时间'),
    sa.Column('updater', sa.String(length=64), nullable=True, comment='更新者'),
    sa.Column('update_time', sa.DateTime(), nullable=False, comment='更新时间'),
    sa.Column('deleted', sa.SmallInteger(), nullable=False, comment='是否删除'),
    sa.Column('tenant_id', sa.BigInteger(), nullable=False, comment='租户编号'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('system_tenant',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False, comment='租户编号'),
    sa.Column('name', sa.String(length=63), nullable=False, comment='租户名'),
    sa.Column('contact_user_id', sa.BigInteger(), nullable=True, comment='联系人编号'),
    sa.Column('contact_name', sa.String(length=64), nullable=False, comment='联系人姓名'),
    sa.Column('contact_mobile', sa.String(length=11), nullable=True, comment='联系手机'),
    sa.Column('status', sa.SmallInteger(), nullable=False, comment='租户状态（0正常 1停用）'),
    sa.Column('domain', sa.String(length=64), nullable=True, comment='绑定域名'),
    sa.Column('package_id', sa.BigInteger(), nullable=False, comment='租户套餐编号'),
    sa.Column('expire_time', sa.DateTime(), nullable=False, comment='过期时间'),
    sa.Column('account_count', sa.Integer(), nullable=False, comment='账号配额'),
    sa.Column('creator', sa.String(length=64), nullable=True, comment='创建者'),
    sa.Column('create_time', sa.DateTime(), nullable=False, comment='创建时间'),
    sa.Column('updater', sa.String(length=64), nullable=True, comment='更新者'),
    sa.Column('update_time', sa.DateTime(), nullable=False, comment='更新时间'),
    sa.Column('deleted', sa.SmallInteger(), nullable=False, comment='是否删除'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('system_tenant_package',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False, comment='套餐编号'),
    sa.Column('name', sa.String(length=30), nullable=False, comment='套餐名'),
    sa.Column('status', sa.SmallInteger(), nullable=False, comment='状态（0正常 1停用）'),
    sa.Column('menu_ids', sa.String(length=2048), nullable=False, comment='关联的菜单编号'),
    sa.Column('remark', sa.String(length=256), nullable=True, comment='备注'),
    sa.Column('creator', sa.String(length=64), nullable=True, comment='创建者'),
    sa.Column('create_time', sa.DateTime(), nullable=False, comment='创建时间'),
    sa.Column('updater', sa.String(length=64), nullable=True, comment='更新者'),
    sa.Column('update_time', sa.DateTime(), nullable=False, comment='更新时间'),
    sa.Column('deleted', sa.SmallInteger(), nullable=False, comment='是否删除'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('system_user_role',
    sa.Column('user_id', sa.BigInteger(), nullable=False, comment='用户ID'),
    sa.Column('role_id', sa.BigInteger(), nullable=False, comment='角色ID'),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False, comment='主键'),
    sa.Column('creator', sa.String(length=64), nullable=True, comment='创建者'),
    sa.Column('create_time', sa.DateTime(), nullable=False, comment='创建时间'),
    sa.Column('updater', sa.String(length=64), nullable=True, comment='更新者'),
    sa.Column('update_time', sa.DateTime(), nullable=False, comment='更新时间'),
    sa.Column('deleted', sa.SmallInteger(), nullable=False, comment='是否删除'),
    sa.Column('tenant_id', sa.BigInteger(), nullable=False, comment='租户编号'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('system_users',
    sa.Column('username', sa.String(length=30), nullable=False, comment='用户账号'),
    sa.Column('password', sa.String(length=100), nullable=False, comment='密码'),
    sa.Column('nickname', sa.String(length=30), nullable=False, comment='用户昵称'),
    sa.Column('remark', sa.String(length=500), nullable=True, comment='备注'),
    sa.Column('dept_id', sa.BigInteger(), nullable=True, comment='部门ID'),
    sa.Column('post_ids', sa.String(length=255), nullable=True, comment='岗位编号数组'),
    sa.Column('email', sa.String(length=50), nullable=True, comment='用户邮箱'),
    sa.Column('mobile', sa.String(length=11), nullable=True, comment='手机号码'),
    sa.Column('sex', sa.SmallInteger(), nullable=True, comment='用户性别'),
    sa.Column('avatar', sa.String(length=512), nullable=True, comment='头像地址'),
    sa.Column('status', sa.SmallInteger(), nullable=False, comment='帐号状态（0正常 1停用）'),
    sa.Column('login_ip', sa.String(length=50), nullable=True, comment='最后登录IP'),
    sa.Column('login_date', sa.DateTime(), nullable=True, comment='最后登录时间'),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False, comment='主键'),
    sa.Column('creator', sa.String(length=64), nullable=True, comment='创建者'),
    sa.Column('create_time', sa.DateTime(), nullable=False, comment='创建时间'),
    sa.Column('updater', sa.String(length=64), nullable=True, comment='更新者'),
    sa.Column('update_time', sa.DateTime(), nullable=False, comment='更新时间'),
    sa.Column('deleted', sa.SmallInteger(), nullable=False, comment='是否删除'),
    sa.Column('tenant_id', sa.BigInteger(), nullable=False, comment='租户编号'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('system_users')
    op.drop_table('system_user_role')
    op.drop_table('system_tenant_package')
    op.drop_table('system_tenant')
    op.drop_table('system_role_menu')
    op.drop_table('system_role')
    op.drop_table('system_post')
    op.drop_table('system_operate_log')
    op.drop_table('system_oauth2_refresh_token')
    op.drop_table('system_oauth2_client')
    op.drop_table('system_oauth2_access_token')
    op.drop_table('system_notice')
    op.drop_table('system_menu')
    op.drop_table('system_login_log')
    op.drop_table('system_dict_type')
    op.drop_table('system_dict_data')
    op.drop_table('system_dept')
    # ### end Alembic commands ###
